services:
  mysql:
    container_name: mysql_docker
    volumes:
      - /Users/kimsuyeon/tools/docker-compose/mysql
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysqldb
      MYSQL_USER : dev_1234
      MYSQL_PASSWORD : 1234
      TZ: Asia/Seoul
    networks:
      - mynetwork
volumes:
  mysql:

networks:
  mynetwork:
    driver: bridge
#test1
